version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    ports:
      - '5432:5432'

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -b redis://redis:6379/0 --app app.tasks worker --loglevel=DEBUG

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade +4 && uvicorn app.main:app --host 0.0.0.0 --port 8888 || uvicorn app.main:app --host 0.0.0.0 --port 8888"
    tty: true
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://user:userpass@postgres:5432/user'
    depends_on:
      - "postgres"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development
